### ISSUE TITLE
Check that John is okay with reuse of the project name

### ISSUE THREAD

**Issue by alerque** [alerque/commonmark-lua#1]
It looks like @jgm started on a Lua module with the name [commonmark-lua](https://github.com/jgm/commonmark-lua) already, but it turned into a set of bindings to `cmark`, but that the project later took on the name [*cmark-lua*](https://github.com/jgm/cmark-lua) and it's CLI counterpart [*lcmark*](https://github.com/jgm/lcmark). John can you confirm I'm not stepping on too many toes by (re)using this name?

It may be a fools errand to try this anyways, but do you mind the project name in the attempt?

**Comment by jgm** [comment]
No problem.  I added a note to my old repository indicated that it was deprecated in favor of cmark-lua.

**Comment by alerque** [comment]
Thanks @jgm. If you don't plan on working on that code base and don't want to accept new issues for it, you might consider setting the Github repository into archive mode too from the "Danger Zone" section at the bottom of [settings](https://github.com/jgm/commonmark-lua/settings). Github puts the whole thing in read-only mode and adds a banner that's a more noticeable indication of the state.

**Comment by jgm** [comment]
I'll do that.
